site_name: BRAIN-v1
site_description: Direct Pixel-Fitting Stellar Population Synthesis Pipeline
site_author: Suresh Parekh

theme:
  name: material
  logo: brainlogo.png
  favicon: brainlogo.png
  features:
    - content.code.annotate
  palette:
    scheme: default
    primary: black
    accent: black

markdown_extensions:

  - pymdownx.arithmatex:
      generic: true
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
